const PRO_KEYS = {
  publicKey: "edgeclose-backup-public-key",
  privateWrap: "edgeclose-backup-private-wrap",
  authHash: "edgeclose-settings-password-hash",
  authSalt: "edgeclose-settings-password-salt",
  authIterations: "edgeclose-settings-password-iterations"
};
const PRO_PBKDF2_ITERATIONS = 310000;
const RECOVERY_PATH = "EdgeClose/recovery-key.enc";
let pendingSetupPassword = "";
let pendingOldPassword = "";
let pendingNewPassword = "";

const b64 = (bytes) => { let s = ""; bytes.forEach((b) => { s += String.fromCharCode(b); }); return btoa(s); };
const unb64 = (s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
const dataUrl = (obj) => `data:application/octet-stream;base64,${b64(new TextEncoder().encode(JSON.stringify(obj)))}`;
async function pbkdf2(password, salt, iterations = PRO_PBKDF2_ITERATIONS) { const k = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveKey"]); return crypto.subtle.deriveKey({ name: "PBKDF2", salt, iterations, hash: "SHA-256" }, k, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }
async function encryptJson(value, key) { const iv = crypto.getRandomValues(new Uint8Array(12)); const cipher = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(JSON.stringify(value))); return { iv: b64(iv), ciphertext: b64(new Uint8Array(cipher)) }; }
async function decryptJson(record, key) { const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: unb64(record.iv) }, key, unb64(record.ciphertext)); return JSON.parse(new TextDecoder().decode(plain)); }
async function generateBackupKeys() { return crypto.subtle.generateKey({ name: "RSA-OAEP", modulusLength: 2048, publicExponent: new Uint8Array([1,0,1]), hash: "SHA-256" }, true, ["encrypt", "decrypt"]); }
async function exportJwk(pair) { return { publicKey: await crypto.subtle.exportKey("jwk", pair.publicKey), privateKey: await crypto.subtle.exportKey("jwk", pair.privateKey) }; }
async function setLocalRecovery(privateJwk, password) { const salt = crypto.getRandomValues(new Uint8Array(16)); const key = await pbkdf2(password, salt); const wrapped = await encryptJson({ privateKey: privateJwk }, key); await chrome.storage.local.set({ [PRO_KEYS.privateWrap]: { kdfIterations: PRO_PBKDF2_ITERATIONS, salt: b64(salt), ...wrapped } }); }
async function getLocalPrivate(password) { const s = await chrome.storage.local.get(PRO_KEYS.privateWrap); const record = s[PRO_KEYS.privateWrap]; if (!record?.salt) throw new Error("Recovery key is not configured"); return decryptJson(record, await pbkdf2(password, unb64(record.salt), Number(record.kdfIterations) || PRO_PBKDF2_ITERATIONS)); }
async function writeRecoveryFile(privateJwk, publicJwk, password) { const salt = crypto.getRandomValues(new Uint8Array(16)); const key = await pbkdf2(password, salt); const encrypted = await encryptJson({ schemaVersion: 1, version: "1.6.0", publicKey: publicJwk, privateKey: privateJwk }, key); const record = { schemaVersion: 1, type: "edgeclose-recovery-key", kdfIterations: PRO_PBKDF2_ITERATIONS, salt: b64(salt), ...encrypted }; await chrome.downloads.download({ url: dataUrl(record), filename: RECOVERY_PATH, saveAs: false, conflictAction: "overwrite" }); }
async function ensureBackupKeys(password) { let s = await chrome.storage.local.get(PRO_KEYS.publicKey); if (s[PRO_KEYS.publicKey]) return s[PRO_KEYS.publicKey]; const pair = await generateBackupKeys(); const jwk = await exportJwk(pair); await chrome.storage.local.set({ [PRO_KEYS.publicKey]: jwk.publicKey }); await setLocalRecovery(jwk.privateKey, password); await writeRecoveryFile(jwk.privateKey, jwk.publicKey, password); return jwk.publicKey; }
async function verifyPassword(password) { const s = await chrome.storage.local.get([PRO_KEYS.authHash, PRO_KEYS.authSalt, PRO_KEYS.authIterations]); if (!s[PRO_KEYS.authHash] || !s[PRO_KEYS.authSalt]) return false; const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveBits"]); const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt: unb64(s[PRO_KEYS.authSalt]), iterations: Number(s[PRO_KEYS.authIterations]) || PRO_PBKDF2_ITERATIONS, hash: "SHA-256" }, key, 256); const actual = unb64(s[PRO_KEYS.authHash]); const got = new Uint8Array(bits); if (actual.length !== got.length) return false; let d = 0; for (let i = 0; i < actual.length; i++) d |= actual[i] ^ got[i]; return d === 0; }
function style() { if (document.getElementById("edgeclose-pro-style")) return; const css = document.createElement("style"); css.id = "edgeclose-pro-style"; css.textContent = `
.pro-control,.backup-panel{margin:0 0 18px;padding:22px;border:1px solid #dbe4e7;border-radius:16px;background:#fff;box-shadow:0 14px 34px rgba(20,47,58,.07)}
.pro-control .pro-title,.backup-panel .pro-title{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.pro-kicker{margin:0 0 6px;color:#1f6feb;font-size:.72rem;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.pro-title h2{margin:0;font-size:1.15rem;letter-spacing:-.02em}.pro-copy{margin:6px 0 16px;color:#66767d;font-size:.82rem;line-height:1.5}.pro-status{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:#eaf8f1;color:#16835b;font-size:.7rem;font-weight:850;white-space:nowrap}.pro-status.paused{background:#fff6de;color:#a36a00}.pro-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.pro-actions button{padding:11px 8px;border:1px solid #dbe4e7;border-radius:10px;background:#f7fafb;color:#172329;font-weight:800}.pro-actions button:hover{border-color:#1f6feb;background:#eaf2ff;color:#1757bd}.pro-actions .resume{grid-column:1/-1;background:#eaf8f1;border-color:#c7e8d8;color:#16835b}.backup-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.backup-card{padding:14px;border:1px solid #dbe4e7;border-radius:12px;background:#f7fafb}.backup-card strong{display:block;font-size:.82rem}.backup-card span{display:block;margin-top:5px;color:#66767d;font-size:.75rem;line-height:1.4}.backup-action{margin-top:10px}.pro-modal{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:20px;background:rgba(13,25,32,.46)}.pro-modal[hidden]{display:none}.pro-dialog{width:min(100%,420px);padding:24px;border:1px solid #dbe4e7;border-radius:16px;background:#fff;box-shadow:0 24px 80px rgba(13,25,32,.25)}.pro-dialog h2{margin:0 0 7px;font-size:1.2rem}.pro-dialog p{margin:0 0 16px;color:#66767d;font-size:.82rem;line-height:1.5}.pro-dialog form{display:grid;gap:11px}.pro-dialog input{max-width:none}.pro-modal-actions{display:flex;justify-content:flex-end;gap:8px}.restore-box{margin-top:14px;padding-top:14px;border-top:1px solid #dbe4e7}.restore-box label{display:grid;gap:6px;margin-bottom:10px;color:#66767d;font-size:.76rem;font-weight:750}.restore-box input[type=file]{max-width:none}.restore-status{min-height:18px;margin-top:8px;color:#b23b36;font-size:.78rem;font-weight:700}@media(max-width:700px){.pro-actions,.backup-grid{grid-template-columns:1fr}.pro-actions .resume{grid-column:auto}}
`; document.head.append(css); }
function addUi() { style(); const protectedContent = document.querySelector("#protected-content"); const authGate = document.querySelector("#auth-gate"); if (!protectedContent || document.getElementById("pro-control")) return;
  const controls = document.createElement("section"); controls.id="pro-control"; controls.className="pro-control"; controls.innerHTML=`<div class="pro-title"><div><p class="pro-kicker">Protection control</p><h2>Temporary pause</h2><p class="pro-copy">Pause is controlled only from this page. Every pause or resume action requires your settings password.</p></div><span id="pro-status" class="pro-status">Protection ON</span></div><div class="pro-actions"><button data-pause="15" type="button">15 minutes</button><button data-pause="60" type="button">1 hour</button><button data-pause="1440" type="button">24 hours</button><button id="pro-resume" class="resume" type="button">Resume protection</button></div>`;
  protectedContent.insertBefore(controls, protectedContent.children[1] || protectedContent.firstChild);
  const backup = document.createElement("section"); backup.className="backup-panel"; backup.innerHTML=`<div class="pro-title"><div><p class="pro-kicker">Persistence</p><h2>Encrypted backup & recovery</h2><p class="pro-copy">Configuration and audit data are maintained as encrypted browser-independent backup files. The recovery key is separately protected by your password.</p></div></div><div class="backup-grid"><div class="backup-card"><strong>Config & audit</strong><span>Encrypted backup: Downloads\EdgeClose\config-audit.enc</span><button id="backup-now" class="secondary-button backup-action" type="button">Backup now</button></div><div class="backup-card"><strong>Recovery key</strong><span>Password-protected RSA private key: Downloads\EdgeClose\recovery-key.enc</span><button id="recovery-refresh" class="secondary-button backup-action" type="button">Refresh recovery key</button></div></div>`;
  protectedContent.insertBefore(backup, protectedContent.children[protectedContent.children.length-1]);
  const restore = document.createElement("section"); restore.className="restore-box"; restore.innerHTML=`<strong>Restore after reinstall</strong><label>Password<input id="restore-password" type="password" autocomplete="current-password"></label><label>Recovery key file<input id="restore-recovery" type="file" accept=".enc,application/json"></label><label>Config & audit backup<input id="restore-config" type="file" accept=".enc,application/json"></label><button id="restore-backup" class="secondary-button" type="button">Restore encrypted backup</button><p id="restore-status" class="restore-status"></p>`;
  authGate.append(restore);
  const modal=document.createElement("div"); modal.className="pro-modal" hidden; modal.id="pro-modal"; modal.innerHTML=`<div class="pro-dialog" role="dialog" aria-modal="true" aria-labelledby="reauth-title"><h2 id="reauth-title">Confirm password</h2><p id="reauth-copy">Enter your settings password to continue.</p><form id="reauth-form"><input id="reauth-password" type="password" autocomplete="current-password" required><div class="pro-modal-actions"><button id="reauth-cancel" class="text-button" type="button">Cancel</button><button class="primary-button" type="submit">Confirm</button></div><p id="reauth-error" class="auth-error"></p></form></div>`; document.body.append(modal);
  function openAuth(copy, onSuccess){ modal.hidden=false; $("#reauth-copy").textContent=copy; $("#reauth-password").value=""; $("#reauth-error").textContent=""; $("#reauth-password").focus(); modal._onSuccess=onSuccess; }
  window.edgecloseReauth=openAuth; $("#reauth-cancel").addEventListener("click",()=>{modal.hidden=true;}); $("#reauth-form").addEventListener("submit",async(e)=>{e.preventDefault(); const pw=$("#reauth-password").value; if(await verifyPassword(pw)){modal.hidden=true; await modal._onSuccess(pw);} else $("#reauth-error").textContent="Incorrect password.";});
  controls.querySelectorAll("[data-pause]").forEach((button)=>button.addEventListener("click",()=>window.edgecloseReauth("Pausing protection is a protected action.", async(pw)=>{const r=await chrome.runtime.sendMessage({type:"edgeclose-pause",minutes:Number(button.dataset.pause)}); if(r?.ok){$("#pro-status").textContent="Protection paused";$("#pro-status").classList.add("paused");refreshDashboardText();await chrome.runtime.sendMessage({type:"edgeclose-audit",event:"protected_pause_requested",metadata:{durationMinutes:Number(button.dataset.pause)}});}})));
  $("#pro-resume").addEventListener("click",()=>window.edgecloseReauth("Resuming protection is a protected action.",async()=>{const r=await chrome.runtime.sendMessage({type:"edgeclose-resume"}); if(r?.ok){$("#pro-status").textContent="Protection ON";$("#pro-status").classList.remove("paused");refreshDashboardText();}}));
  $("#backup-now").addEventListener("click",()=>window.edgecloseReauth("Create an encrypted configuration and audit backup.",async()=>{const r=await chrome.runtime.sendMessage({type:"edgeclose-backup-now"}); $("#backup-now").textContent=r?.ok?"Backup created":"Backup failed"; setTimeout(()=>$("#backup-now").textContent="Backup now",2200);}));
  $("#recovery-refresh").addEventListener("click",()=>window.edgecloseReauth("Refresh the password-protected recovery key.",async(pw)=>{try{await ensureBackupKeys(pw);const s=await chrome.storage.local.get(PRO_KEYS.publicKey);const priv=await getLocalPrivate(pw);await writeRecoveryFile(priv.privateKey,s[PRO_KEYS.publicKey],pw);$("#recovery-refresh").textContent="Recovery key refreshed";}catch{$("#recovery-refresh").textContent="Recovery refresh failed";}setTimeout(()=>$("#recovery-refresh").textContent="Refresh recovery key",2400);}));
  $("#restore-backup").addEventListener("click",restoreBackup);
  new MutationObserver(()=>refreshDashboardText()).observe(document.body,{subtree:true,childList:true});
}
function refreshDashboardText(){ const p=document.getElementById("pause-state"); const s=document.getElementById("pro-status"); if(p&&s&&!s.classList.contains("paused")) p.textContent="Pause/resume is controlled here and requires password confirmation."; }
async function restoreBackup(){ const status=document.getElementById("restore-status"); status.textContent=""; const pw=document.getElementById("restore-password").value; const rf=document.getElementById("restore-recovery").files?.[0]; const cf=document.getElementById("restore-config").files?.[0]; if(!pw||!rf||!cf){status.textContent="Select both backup files and enter the backup password.";return;} try{const recovery=JSON.parse(await rf.text()); const rkey=await pbkdf2(pw,unb64(recovery.salt),Number(recovery.kdfIterations)||PRO_PBKDF2_ITERATIONS); const recovered=await decryptJson(recovery,rkey); const privateKey=await crypto.subtle.importKey("jwk",recovered.privateKey,{name:"RSA-OAEP",hash:"SHA-256"},false,["decrypt"]); const config=JSON.parse(await cf.text()); const wrapped=await crypto.subtle.decrypt({name:"RSA-OAEP"},privateKey,unb64(config.wrappedKey)); const aes=await crypto.subtle.importKey("raw",wrapped,{name:"AES-GCM"},false,["decrypt"]); const payload=await decryptJson(config,aes); if(!payload.auth?.hash||!payload.auth?.salt) throw new Error("Invalid backup"); const good=await verifyBackupPassword(pw,payload.auth); if(!good) throw new Error("Wrong password"); await chrome.storage.local.set({sites:Array.isArray(payload.sites)?payload.sites:[], "edgeclose-audit-log":Array.isArray(payload.audit)?payload.audit:[], "edgeclose-pause-until":Number(payload.pauseUntil)||0, [PRO_KEYS.authHash]:payload.auth.hash, [PRO_KEYS.authSalt]:payload.auth.salt, [PRO_KEYS.authIterations]:payload.auth.iterations, [PRO_KEYS.publicKey]:recovered.publicKey}); await setLocalRecovery(recovered.privateKey,pw); status.textContent="Backup restored. Reloading…"; setTimeout(()=>location.reload(),700);}catch(error){status.textContent=error?.message||"Could not restore backup.";} }
async function verifyBackupPassword(password,auth){ const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]); const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:unb64(auth.salt),iterations:Number(auth.iterations)||PRO_PBKDF2_ITERATIONS,hash:"SHA-256"},key,256); const got=new Uint8Array(bits), actual=unb64(auth.hash); if(got.length!==actual.length)return false;let d=0;for(let i=0;i<got.length;i++)d|=got[i]^actual[i];return d===0;}

const $ = (s) => document.querySelector(s);
function wirePasswordLifecycle(){ const setup=$("#setup-form"), change=$("#change-password-form"); setup?.addEventListener("submit",()=>{pendingSetupPassword=$("#setup-password")?.value||"";}); change?.addEventListener("submit",()=>{pendingOldPassword=$("#current-password")?.value||"";pendingNewPassword=$("#new-password")?.value||"";}); chrome.storage.onChanged.addListener(async(changes,area)=>{if(area!=="local"||!changes[PRO_KEYS.authHash])return; try{if(pendingSetupPassword){const publicJwk=await ensureBackupKeys(pendingSetupPassword);await chrome.storage.local.set({[PRO_KEYS.publicKey]:publicJwk});pendingSetupPassword="";}else if(pendingOldPassword&&pendingNewPassword){const priv=(await getLocalPrivate(pendingOldPassword)).privateKey;await setLocalRecovery(priv,pendingNewPassword);const s=await chrome.storage.local.get(PRO_KEYS.publicKey);if(s[PRO_KEYS.publicKey])await writeRecoveryFile(priv,s[PRO_KEYS.publicKey],pendingNewPassword);pendingOldPassword="";pendingNewPassword="";} await chrome.runtime.sendMessage({type:"edgeclose-backup-now"});}catch{pendingSetupPassword="";pendingOldPassword="";pendingNewPassword="";}}); }
addUi();
wirePasswordLifecycle();
